name: Stream Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Force workflow run by creating dummy env var
        run: echo "DUMMY_RUN=$(date +%s)" >> $GITHUB_ENV

      - name: Create .env file from secrets
        run: |
          echo "BASE_URL0=${{ secrets.BASE_URL0 }}" >> .env
          echo "BASE_URL1=${{ secrets.BASE_URL1 }}" >> .env
          echo "BASE_URL2=${{ secrets.BASE_URL2 }}" >> .env
          echo "BASE_URL4=${{ secrets.BASE_URL4 }}" >> .env
          echo "BASE_URL5=${{ secrets.BASE_URL5 }}" >> .env
          echo "BASE_URL6=${{ secrets.BASE_URL6 }}" >> .env
          echo "BASE_URL8=${{ secrets.BASE_URL8 }}" >> .env
          echo "BASE_URL9=${{ secrets.BASE_URL9 }}" >> .env
          echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> .env
          echo "WEB_DOMAIN=${{ secrets.WEB_DOMAIN }}" >> .env

      - name: Print current UTC time (debug)
        run: date -u

      - name: Run Stream Monitor script
        run: python main.py
